[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tossingbot"
version = "1.0.0"
requires-python = ">=3.8"
dependencies = [
    "robot-client",
]

[tool.setuptools]
package-dir = {"" = "src/main"}
packages = ["tossingbot"]

[tool.pylance]
include = ["src/main/tossingbot"]
